/**
 /**
 * User: Luca
 * Date: 16/02/15
 */
'use strict';

var BULKING_FILE_TARGETS = {
  BULKING_HERMES_COMMINV_IMPORT_TARGET       : 'commercialInvoice_Import',
  BULKING_HERMES_COMMINV_EXPORT_TARGET       : 'commercialInvoice_Export',
  BULKING_HERMES_IMPORT_DECLARATION_TARGET   : 'importDeclaration',
  BULKING_HERMES_UTISLI_TARGET               : 'utisli'
};

var prefix = 'bulkings_';
var BULKING_REFCOLLECTIONS = {
  BULKING_HERMES_COMMINV_IMPORT_REF     : prefix + BULKING_FILE_TARGETS.BULKING_HERMES_COMMINV_IMPORT_TARGET,
  BULKING_HERMES_COMMINV_EXPORT_REF     : prefix + BULKING_FILE_TARGETS.BULKING_HERMES_COMMINV_EXPORT_TARGET,
  BULKING_HERMES_IMPORT_DECLARATION_REF : prefix + BULKING_FILE_TARGETS.BULKING_HERMES_IMPORT_DECLARATION_TARGET,
  BULKING_HERMES_UTISLI_REF             : prefix + BULKING_FILE_TARGETS.BULKING_HERMES_UTISLI_TARGET
};

module.exports = {
  BULKING_REFCOLLECTIONS : BULKING_REFCOLLECTIONS,
  BULKING_FILE_TARGETS  : BULKING_FILE_TARGETS
};
